name: Build Site

on:
  push:
    branches: [ "build-test" ]
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-sass:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 14.x

      - name: Run node-sass and copy assets
        run: |
          npm install
          npm rebuild node-sass
          npm run uswds-copy-assets
          npm run uswds-copy-theme
          npm run uswds-build-sass
  
  build-site:
    needs: build-sass
    
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
        
      - name: Setup Ruby
        uses: ruby/setup-ruby@55283cc23133118229fd3f97f9336ee23a179fcf # v1.146.0
        with:
          ruby-version: '3.1'
          bundler-cache: true
          cache-version: 0
      
      - name: Build with Jekyll
        run: bundle exec jekyll build
